### PR TITLE
Fix installation in virtual environments

### LINKED ISSUE #3: setup.py has an undeclared build dependency on docutils and sphinx, which breaks pip
This looks like a bug:

```
.venv/bin/pip -q install -r requirements.txt
  WARNING: Generating metadata for package cairocffi produced metadata for project name unknown. Fix your #egg=cairocffi fragments.
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-43iaayx9/sphinxcontrib-domaintools/setup.py", line 11, in <module>
        import domaintools
      File "sphinxcontrib/domaintools.py", line 25, in <module>
        from docutils import nodes
    ImportError: No module named 'docutils'
```

Caused by these lines:

https://github.com/sphinx-contrib/domaintools/blob/eb19a11a7d07af0cf20913290f55b8f07063b2cb/setup.py#L10-L17

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes #3 

This is copied from https://github.com/sphinx-contrib/napoleon.

Tested with:
```
$ python3 -m venv .venv
$ .venv/bin/pip -q install --upgrade pip
$ .venv/bin/pip install .
```

Pinging @klorenz, since I'm not sure you'll be notified automatically.

### CODE REVIEW

**Comment by eric-wieser** [comment]
@tk0miya: I know this is @sphinx-contrib and not @sphinx-doc, but do you have maintainer power over this repo / its PyPI entry?

**Comment by tk0miya** [comment]
Yes, I have administrator role of this repo. But I don't have permission of PyPI. So I can't maintain this package.

**Comment by eric-wieser** [comment]
I sent an email to @klorenz asking if they could take a look, and whether they'd be willing to grant PyPI maintainer status to you. Failing that, I suppose we could create:

* `sphinx-contrib/domaintools2`
* `sphinx-contrib/cmakedomain2` (no changes other than replacing the domaintools dependency)
* `sphinx-contrib/makedomain2` (no changes other than replacing the domaintools dependency)

Alternatively, it might be possible to invoke [PEP-541](https://www.python.org/dev/peps/pep-0541/) to transfer ownership

**Comment by eric-wieser** [comment]
I opened https://github.com/pypa/warehouse/issues/6190 to kickstart the PEP-541 process, since it takes a long time, and give klorenz plenty of time to appear.

**Comment by tk0miya** [comment]
To be sustainable, it might be better to give administration privileges to Sphinx team (as co-maintainer). But main maintainer must be still needed. Because Sphinx team is too small to keep maintain all sphinx-contrib modules.

So far, there are no rules to manage packages under sphinx-contrib. So we need to discuss more for new framework. @stephenfin @shimizukawa @birkenfeld  what do you think?


Note: Nowadays, it became much easier to publish own package to world than once. The package index (PyPI) has been much grown, and everybody can search packages easily. In Addition, GitHub and other online repositories helps us to publish own OSS products. So, IMO, the importance of sphinx-contrib has been less. So we also need to discuss about future of sphinx-contrib.

**Comment by stephenfin** [comment]
> Note: Nowadays, it became much easier to publish own package to world than once. The package index (PyPI) has been much grown, and everybody can search packages easily. In Addition, GitHub and other online repositories helps us to publish own OSS products. So, IMO, the importance of sphinx-contrib has been less. So we also need to discuss about future of sphinx-contrib.

I think the main reason for sphinx-contrib to continue to exist is to help share the burden of maintaining plugins. However, for that to happen we do need to ensure PyPI is also configured to allow other users from the `sphinx-contrib` organization to maintain a package. Sounds like @eric-wieser is on track here to sort that out, assuming we don't hear back from @klorenz

**Comment by eric-wieser** [comment]
@tk0miya, would you mind commenting on https://github.com/pypa/warehouse/issues/6190 to indicate that you are in favor of being assigned maintainership status on this package?

**Comment by tk0miya** [comment]
>However, for that to happen we do need to ensure PyPI is also configured to allow other users from the sphinx-contrib organization to maintain a package.

At present, `sphinx-contrib` is mere a shared repository of extensions. It means the owners does not pass a permissions of package management. AFAIK, Sphinx team never control it.
So, to realize your idea, we need to build a team to maintain orphaned packages, and get permissions to co-maintain the package from owners.

**Comment by stephenfin** [comment]
> > However, for that to happen we do need to ensure PyPI is also configured to allow other users from the sphinx-contrib organization to maintain a package.
> 
> At present, `sphinx-contrib` is mere a shared repository of extensions. It means the owners does not pass a permissions of package management. AFAIK, Sphinx team never control it.
> So, to realize your idea, we need to build a team to maintain orphaned packages, and get permissions to co-maintain the package from owners.


I already have a `sphinx-contrib` user for this purpose. I'd be happy to adopt it under that. This would ideally be an organization but PyPI doesn't support those yet (I'm working on it when I can)

**Comment by eric-wieser** [comment]
For anyone following along, maintainership has been granted on PyPI to @tk0miya

**Comment by tk0miya** [comment]
I post a call for maintainer as #6. So let's discuss about it on the issue.

Now I'm going to merge this.

**Pull request merged**
